[book]
authors = [
  "Maja Mataric",
  "Ross Mead",
  "Mark Yim",
  "Simon Kim",
  "Andrew Specian",
  "Braden McDorman",
]
language = "en"
multilingual = false
src = "src"
title = "Quori v1 Documentation"
